// app/data.ts

export const projects = [
  {
    title: "Smart Parking Management System",
    category: "IoT Application",
    duration: "2025",
    techStack: ["ESP32", "Arduino", "RFID", "Ultrasonic Sensors", "Firebase", "React"],
    description: "An IoT-based smart parking management solution that monitors parking slot availability in real time and guides users to vacant parking spaces. The system helps reduce traffic congestion, improves parking efficiency, and automates parking operations.",
    keyFeatures: [
      "Real-time parking slot monitoring",
      "RFID-based vehicle authentication",
      "Live dashboard for slot availability",
      "Automated entry and exit management",
      "Cloud synchronization using Firebase",
      "Mobile-friendly interface",
    ],
    github: "https://github.com/nishaa-11",
    demo: "Coming Soon",
  },
  {
    title: "Civic Issue Resolution System",
    category: "Full Stack Web Application",
    duration: "2025",
    techStack: ["Next.js", "React", "Node.js", "Express", "MongoDB"],
    description: "A civic engagement platform that enables citizens to report infrastructure issues such as potholes, waste accumulation, water leakage, and public facility problems while allowing authorities to track and resolve complaints efficiently.",
    keyFeatures: [
      "Image-based issue reporting",
      "Location-based complaint mapping",
      "Complaint tracking system",
      "Authority management dashboard",
      "User notifications",
      "Analytics and reporting",
    ],
    github: "https://github.com/nishaa-11",
    demo: "Coming Soon",
  },
  {
    title: "DateVerse",
    category: "Full Stack Social Platform",
    duration: "2025",
    techStack: ["Next.js", "React", "Node.js", "MongoDB"],
    description: "A modern event and social discovery platform that helps users discover, create, and manage events while connecting with communities and like-minded individuals.",
    keyFeatures: [
      "User authentication",
      "Event management",
      "Community discovery",
      "Real-time updates",
      "Responsive design",
    ],
    github: "https://github.com/nishaa-11",
    demo: "Coming Soon",
  },
  {
    title: "AI Resume Analyzer",
    category: "AI Application",
    duration: "2025",
    techStack: ["Python", "Flask", "OpenAI API"],
    description: "An AI-powered resume analysis tool that evaluates resumes against job descriptions and provides recommendations to improve ATS compatibility and hiring potential.",
    keyFeatures: [
      "Resume parsing",
      "ATS scoring",
      "Keyword analysis",
      "AI-powered suggestions",
      "Job matching insights",
    ],
    github: "https://github.com/nishaa-11",
    demo: "Coming Soon",
  },
  {
    title: "Portfolio Website",
    category: "Frontend Development",
    duration: "2025",
    techStack: ["Next.js", "TypeScript", "Tailwind CSS", "Framer Motion"],
    description: "A modern developer portfolio designed with smooth animations, responsive layouts, and clean user experience principles to showcase projects and achievements.",
    keyFeatures: [
      "Responsive design",
      "Smooth scrolling",
      "Interactive navigation",
      "Dark theme UI",
      "Framer Motion animations",
    ],
    github: "https://github.com/nishaa-11/Portfolio-v1",
    demo: "Coming Soon",
  },
  {
    title: "AI Study Assistant",
    category: "Educational AI Platform",
    duration: "2025",
    techStack: ["Python", "FastAPI", "React"],
    description: "An intelligent study companion that helps students generate notes, summaries, quizzes, and personalized learning plans using AI.",
    keyFeatures: [
      "AI-generated notes",
      "Quiz generation",
      "Learning recommendations",
      "Progress tracking",
      "Smart study plans",
    ],
    github: "https://github.com/nishaa-11",
    demo: "Coming Soon",
  },
];
